[package]
name = "tetrahedrane"
version = "0.1.0"
authors = ["ca1ek <ca1ek@users.noreply.github.com>"]

[dependencies]
orbclient = { git = "https://github.com/redox-os/orbclient" }
sinulation = { git = "https://github.com/Ticki/sinulation" }